import * as React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import { helloWorld } from 'engine';

const Home: NextPage = () => {
  const message = helloWorld();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{message}</h1>
      </main>
    </div>
  );
};

export default Home;
