import * as React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Button } from 'ui';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <h1>Hello, world.</h1>

      <Button onClick={() => console.log('hello')} />
    </main>
  </div>
);

export default Home;
